name: Publish package distributions to PyPI

on:
  push:
    tags:
      - "*"
  workflow_call: # can be triggered by other actions

jobs:
  pypi:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/sphinxnotes-project
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
    - uses: actions/checkout@v4
    - run: git fetch --prune --unshallow --tags
    - uses: actions/setup-python@v5
    - run: pip install build twine && make dist
    - uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
