name: Tag every commit

on:
  push:
    branches:
      - master
      - tag-every-commit

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }} # anothrNick/github-tag-action#266
          fetch-depth: '0'
      - uses: anothrNick/github-tag-action@v1
        env:
          CUSTOM_TAG: "1.0a${{ github.run_number }}"
