name: Tag every commit

on:
  push:
    branches:
      - master
      - tag-every-commit

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_TAG: 1.0a${{ github.run_number }}
  publish:
    uses: ./.github/workflows/pypi.yml
    needs: tag
    with:
      github_ref: 1.0a${{ github.run_number }}
