name: Tag and Publish every commit

on:
  push:
    branches:
      - master
      - tag-every-commit

jobs:
  tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.new_tag }}
    permissions:
      contents: write
    environment:
      name: pypi
      url: https://pypi.org/p/sphinxnotes-project
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - uses: anothrNick/github-tag-action@v1
        id: tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_TAG: 1.0a${{ github.run_number }}
  publish:
    uses: ./.github/workflows/pypi.yml
    needs: tag
    with:
      ref: ${{ needs.tag.outputs.tag }} 
